[project]
name = "realtime-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.2",
    "pyaudio>=0.2.14",
    "python-dotenv>=1.0.1",
    "soundfile>=0.12.1",
    "websockets>=13.1",
]
